name: EconomyNPC
main: com.mongoosecountry.pete800.EconomyNPC
version: 2.0
commands:
    enpc:
      description: EconomyNPC related commands
    tokens:
      description: EconomyNPC token commands
      aliases: [token]
depend: [Vault]
